apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flimg
  name: flimg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flimg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flimg
    spec:
      containers:
      - image: hruthingali/myimage
        name: myimage
        resources: {}
status: {}
