apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flimg
  name: flimg
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flimg
  type: NodePort
status:
  loadBalancer: {}
